backend = "glx";
vsync = true;
shadow = false;
fading = false;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
blur-method = "none";
detect-rounded-corners = false;
use-damage = true;
